const usersData = [
  {id: 0, name: 'John Doe', address: 'Ha Noi', phone: '0123456789', email: 'Pending', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 1, name: 'Samppa Nori', address: 'Ha Noi', phone: '0123456789', email: 'Active', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 2, name: 'Estavan Lykos', address: 'Ha Noi', phone: '0123456789', email: 'Banned', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 3, name: 'Chetan Mohamed', address: 'Ha Noi', phone: '0123456789', email: 'Inactive', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 4, name: 'Derick Maximinus', address: 'Ha Noi', phone: '0123456789', email: 'Pending', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 5, name: 'Friderik Dávid', address: 'Ha Noi', phone: '0123456789', email: 'Active', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 6, name: 'Yiorgos Avraamu', address: 'Ha Noi', phone: '0123456789', email: 'Active', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 7, name: 'Avram Tarasios', address: 'Ha Noi', phone: '0123456789', email: 'Banned', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 8, name: 'Quintin Ed', address: 'Ha Noi', phone: '0123456789', email: 'Inactive', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 9, name: 'Enéas Kwadwo', address: 'Ha Noi', phone: '0123456789', email: 'Pending', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 10, name: 'Agapetus Tadeáš', address: 'Ha Noi', phone: '0123456789', email: 'Active', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 11, name: 'Carwyn Fachtna', address: 'Ha Noi', phone: '0123456789', email: 'Active', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 12, name: 'Nehemiah Tatius', address: 'Ha Noi', phone: '0123456789', email: 'Banned', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 13, name: 'Ebbe Gemariah', address: 'Ha Noi', phone: '0123456789', email: 'Inactive', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 14, name: 'Eustorgios Amulius', address: 'Ha Noi', phone: '0123456789', email: 'Pending', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 15, name: 'Leopold Gáspár', address: 'Ha Noi', phone: '0123456789', email: 'Active', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 16, name: 'Pompeius René', address: 'Ha Noi', phone: '0123456789', email: 'Active', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 17, name: 'Paĉjo Jadon', address: 'Ha Noi', phone: '0123456789', email: 'Banned', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 18, name: 'Micheal Mercurius', address: 'Ha Noi', phone: '0123456789', email: 'Inactive', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 19, name: 'Ganesha Dubhghall', address: 'Ha Noi', phone: '0123456789', email: 'Pending', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 20, name: 'Hiroto Šimun', address: 'Ha Noi', phone: '0123456789', email: 'Active', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 21, name: 'Vishnu Serghei', address: 'Ha Noi', phone: '0123456789', email: 'Active', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 22, name: 'Zbyněk Phoibos', address: 'Ha Noi', phone: '0123456789', email: 'Banned', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 23, name: 'Einar Randall', address: 'Ha Noi', phone: '0123456789', email: 'Inactive', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 24, name: 'Félix Troels', address: 'Ha Noi', phone: '0123456789', email: 'Active', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 25, name: 'Aulus Agmundr', address: 'Ha Noi', phone: '0123456789', email: 'Pending', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'},
  {id: 42, name: 'Ford Prefex', address: '2001/05/21', phone: 'Alien', email: 'Don\'t panic!', facebook: 'facebook', twitter: 'twitter', instagram: 'instagram'}
]

export default usersData
